#ifndef PROJ_2_BULLET_HELL_PLAYERSTATE_H
#define PROJ_2_BULLET_HELL_PLAYERSTATE_H

enum PlayerState {
    MOVING_RIGHT = 0,
    MOVING_LEFT = 1,
    MOVING_UP = 2,
    MOVING_DOWN = 3,
    STANDING = 4
};

#endif //PROJ_2_BULLET_HELL_PLAYERSTATE_H
